// Country name -> FIPS 10-4 country code, for auto-filling the "Country
// Code (FIPS/ISO)" field from the physical address's country (see
// AdminMissionaryForm.jsx / AdminOrganizationForm.jsx). Uses the exact
// same country names as COUNTRY_CONTINENTS (./countryContinents.js) so
// every entry there either has a FIPS code here or is deliberately
// omitted below.
//
// FIPS 10-4 is genuinely different from ISO 3166-1 alpha-2 for many
// countries -- this is the whole reason auto-fill is useful rather than
// redundant. Some examples: Philippines is RP (not PH), Bolivia is BL
// (not BO), Cambodia is CB (not KH), Japan is JA (not JP), Vietnam is VM
// (not VN), Mongolia is MG (not MN), Zambia is ZA (not the ISO code for
// South Africa that "ZA" looks like it should be). The Joshua Project API
// (see backend/src/utils/joshuaProject.js) expects FIPS-style codes
// specifically, which is why this field exists as a separate value from
// the address's country name at all.
//
// A handful of COUNTRY_CONTINENTS entries have no single clean FIPS
// mapping and are deliberately left out here (auto-fill just won't fire
// for these -- manual entry still works): Åland Islands (no distinct FIPS
// code, treated as part of Finland), Caribbean Netherlands (no single
// code covering Bonaire/Sint Eustatius/Saba), and Palestine (FIPS splits
// this into separate Gaza Strip/West Bank codes with no unified one).
export const COUNTRY_FIPS_CODES = {
  Afghanistan: "AF",
  Albania: "AL",
  Algeria: "AG",
  "American Samoa": "AQ",
  Andorra: "AN",
  Angola: "AO",
  Anguilla: "AV",
  Antarctica: "AY",
  "Antigua and Barbuda": "AC",
  Argentina: "AR",
  Armenia: "AM",
  Aruba: "AA",
  Australia: "AS",
  Austria: "AU",
  Azerbaijan: "AJ",
  Bahamas: "BF",
  Bahrain: "BA",
  Bangladesh: "BG",
  Barbados: "BB",
  Belarus: "BO",
  Belgium: "BE",
  Belize: "BH",
  Benin: "BN",
  Bermuda: "BD",
  Bhutan: "BT",
  Bolivia: "BL",
  "Bosnia and Herzegovina": "BK",
  Botswana: "BC",
  "Bouvet Island": "BV",
  Brazil: "BR",
  "British Indian Ocean Territory": "IO",
  "British Virgin Islands": "VI",
  Brunei: "BX",
  Bulgaria: "BU",
  "Burkina Faso": "UV",
  Burundi: "BY",
  Cambodia: "CB",
  Cameroon: "CM",
  Canada: "CA",
  "Cape Verde": "CV",
  "Cayman Islands": "CJ",
  "Central African Republic": "CT",
  Chad: "CD",
  Chile: "CI",
  China: "CH",
  "Christmas Island": "KT",
  "Cocos (Keeling) Islands": "CK",
  Colombia: "CO",
  Comoros: "CN",
  Congo: "CF",
  "Cook Islands": "CW",
  "Costa Rica": "CS",
  Croatia: "HR",
  Cuba: "CU",
  "Curaçao": "UC",
  Cyprus: "CY",
  Czechia: "EZ",
  Denmark: "DA",
  Djibouti: "DJ",
  Dominica: "DO",
  "Dominican Republic": "DR",
  "DR Congo": "CG",
  Ecuador: "EC",
  Egypt: "EG",
  "El Salvador": "ES",
  "Equatorial Guinea": "EK",
  Eritrea: "ER",
  Estonia: "EN",
  Eswatini: "WZ",
  Ethiopia: "ET",
  "Falkland Islands": "FK",
  "Faroe Islands": "FO",
  Fiji: "FJ",
  Finland: "FI",
  France: "FR",
  "French Guiana": "FG",
  "French Polynesia": "FP",
  "French Southern and Antarctic Lands": "FS",
  Gabon: "GB",
  Gambia: "GA",
  Georgia: "GG",
  Germany: "GM",
  Ghana: "GH",
  Gibraltar: "GI",
  Greece: "GR",
  Greenland: "GL",
  Grenada: "GJ",
  Guadeloupe: "GP",
  Guam: "GQ",
  Guatemala: "GT",
  Guernsey: "GK",
  Guinea: "GV",
  "Guinea-Bissau": "PU",
  Guyana: "GY",
  Haiti: "HA",
  "Heard Island and McDonald Islands": "HM",
  Honduras: "HO",
  "Hong Kong": "HK",
  Hungary: "HU",
  Iceland: "IC",
  India: "IN",
  Indonesia: "ID",
  Iran: "IR",
  Iraq: "IZ",
  Ireland: "EI",
  "Isle of Man": "IM",
  Israel: "IS",
  Italy: "IT",
  "Ivory Coast": "IV",
  Jamaica: "JM",
  Japan: "JA",
  Jersey: "JE",
  Jordan: "JO",
  Kazakhstan: "KZ",
  Kenya: "KE",
  Kiribati: "KR",
  Kosovo: "KV",
  Kuwait: "KU",
  Kyrgyzstan: "KG",
  Laos: "LA",
  Latvia: "LG",
  Lebanon: "LE",
  Lesotho: "LT",
  Liberia: "LI",
  Libya: "LY",
  Liechtenstein: "LS",
  Lithuania: "LH",
  Luxembourg: "LU",
  Macau: "MC",
  Madagascar: "MA",
  Malawi: "MI",
  Malaysia: "MY",
  Maldives: "MV",
  Mali: "ML",
  Malta: "MT",
  "Marshall Islands": "RM",
  Martinique: "MB",
  Mauritania: "MR",
  Mauritius: "MP",
  Mayotte: "MF",
  Mexico: "MX",
  Micronesia: "FM",
  Moldova: "MD",
  Monaco: "MN",
  Mongolia: "MG",
  Montenegro: "MJ",
  Montserrat: "MH",
  Morocco: "MO",
  Mozambique: "MZ",
  Myanmar: "BM",
  Namibia: "WA",
  Nauru: "NR",
  Nepal: "NP",
  Netherlands: "NL",
  "New Caledonia": "NC",
  "New Zealand": "NZ",
  Nicaragua: "NU",
  Niger: "NG",
  Nigeria: "NI",
  Niue: "NE",
  "Norfolk Island": "NF",
  "North Korea": "KN",
  "North Macedonia": "MK",
  "Northern Mariana Islands": "CQ",
  Norway: "NO",
  Oman: "MU",
  Pakistan: "PK",
  Palau: "PS",
  Panama: "PM",
  "Papua New Guinea": "PP",
  Paraguay: "PA",
  Peru: "PE",
  Philippines: "RP",
  "Pitcairn Islands": "PC",
  Poland: "PL",
  Portugal: "PO",
  "Puerto Rico": "RQ",
  Qatar: "QA",
  "Réunion": "RE",
  Romania: "RO",
  Russia: "RS",
  Rwanda: "RW",
  "Saint Barthélemy": "TB",
  "Saint Helena, Ascension and Tristan da Cunha": "SH",
  "Saint Kitts and Nevis": "SC",
  "Saint Lucia": "ST",
  "Saint Martin": "RN",
  "Saint Pierre and Miquelon": "SB",
  "Saint Vincent and the Grenadines": "VC",
  Samoa: "WS",
  "San Marino": "SM",
  "São Tomé and Príncipe": "TP",
  "Saudi Arabia": "SA",
  Senegal: "SG",
  Serbia: "RI",
  Seychelles: "SE",
  "Sierra Leone": "SL",
  Singapore: "SN",
  "Sint Maarten": "NN",
  Slovakia: "LO",
  Slovenia: "SI",
  "Solomon Islands": "BP",
  Somalia: "SO",
  "South Africa": "SF",
  "South Georgia": "SX",
  "South Korea": "KS",
  "South Sudan": "OD",
  Spain: "SP",
  "Sri Lanka": "CE",
  Sudan: "SU",
  Suriname: "NS",
  "Svalbard and Jan Mayen": "SV",
  Sweden: "SW",
  Switzerland: "SZ",
  Syria: "SY",
  Taiwan: "TW",
  Tajikistan: "TI",
  Tanzania: "TZ",
  Thailand: "TH",
  "Timor-Leste": "TT",
  Togo: "TO",
  Tokelau: "TL",
  Tonga: "TN",
  "Trinidad and Tobago": "TD",
  Tunisia: "TS",
  "Türkiye": "TU",
  Turkmenistan: "TX",
  "Turks and Caicos Islands": "TK",
  Tuvalu: "TV",
  Uganda: "UG",
  Ukraine: "UP",
  "United Arab Emirates": "AE",
  "United Kingdom": "UK",
  "United States": "US",
  "United States Minor Outlying Islands": "UM",
  "United States Virgin Islands": "VQ",
  Uruguay: "UY",
  Uzbekistan: "UZ",
  Vanuatu: "NH",
  "Vatican City": "VT",
  Venezuela: "VE",
  Vietnam: "VM",
  "Wallis and Futuna": "WF",
  "Western Sahara": "WI",
  Yemen: "YM",
  Zambia: "ZA",
  Zimbabwe: "ZI",
  Turkey: "TU", // alias for Türkiye
  "Czech Republic": "EZ", // alias for Czechia
  Swaziland: "WZ", // alias for Eswatini
  Burma: "BM", // alias for Myanmar
  Macedonia: "MK", // alias for North Macedonia
  "Democratic Republic of the Congo": "CG", // alias for DR Congo
};

export function getFipsCode(countryName) {
  return COUNTRY_FIPS_CODES[countryName] || null;
}
