// Country name -> continent, for the country/continent filters on the
// public directory and admin partners pages. Uses the exact same country
// names (including aliases like "Turkey" for "Türkiye") as
// backend/src/utils/maskData.js's COUNTRY_CENTROIDS, sourced from the same
// dataset (mledoze/countries, MIT-licensed,
// github.com/mledoze/countries) — kept in sync so "does this app recognize
// this country" means the same thing everywhere it comes up (map pins,
// country filter, continent filter).
export const COUNTRY_CONTINENTS = {
  Afghanistan: "Asia",
  "Åland Islands": "Europe",
  Albania: "Europe",
  Algeria: "Africa",
  "American Samoa": "Oceania",
  Andorra: "Europe",
  Angola: "Africa",
  Anguilla: "Americas",
  Antarctica: "Antarctic",
  "Antigua and Barbuda": "Americas",
  Argentina: "Americas",
  Armenia: "Asia",
  Aruba: "Americas",
  Australia: "Oceania",
  Austria: "Europe",
  Azerbaijan: "Asia",
  Bahamas: "Americas",
  Bahrain: "Asia",
  Bangladesh: "Asia",
  Barbados: "Americas",
  Belarus: "Europe",
  Belgium: "Europe",
  Belize: "Americas",
  Benin: "Africa",
  Bermuda: "Americas",
  Bhutan: "Asia",
  Bolivia: "Americas",
  "Bosnia and Herzegovina": "Europe",
  Botswana: "Africa",
  "Bouvet Island": "Antarctic",
  Brazil: "Americas",
  "British Indian Ocean Territory": "Africa",
  "British Virgin Islands": "Americas",
  Brunei: "Asia",
  Bulgaria: "Europe",
  "Burkina Faso": "Africa",
  Burundi: "Africa",
  Cambodia: "Asia",
  Cameroon: "Africa",
  Canada: "Americas",
  "Cape Verde": "Africa",
  "Caribbean Netherlands": "Americas",
  "Cayman Islands": "Americas",
  "Central African Republic": "Africa",
  Chad: "Africa",
  Chile: "Americas",
  China: "Asia",
  "Christmas Island": "Oceania",
  "Cocos (Keeling) Islands": "Oceania",
  Colombia: "Americas",
  Comoros: "Africa",
  Congo: "Africa",
  "Cook Islands": "Oceania",
  "Costa Rica": "Americas",
  Croatia: "Europe",
  Cuba: "Americas",
  "Curaçao": "Americas",
  Cyprus: "Europe",
  Czechia: "Europe",
  Denmark: "Europe",
  Djibouti: "Africa",
  Dominica: "Americas",
  "Dominican Republic": "Americas",
  "DR Congo": "Africa",
  Ecuador: "Americas",
  Egypt: "Africa",
  "El Salvador": "Americas",
  "Equatorial Guinea": "Africa",
  Eritrea: "Africa",
  Estonia: "Europe",
  Eswatini: "Africa",
  Ethiopia: "Africa",
  "Falkland Islands": "Americas",
  "Faroe Islands": "Europe",
  Fiji: "Oceania",
  Finland: "Europe",
  France: "Europe",
  "French Guiana": "Americas",
  "French Polynesia": "Oceania",
  "French Southern and Antarctic Lands": "Antarctic",
  Gabon: "Africa",
  Gambia: "Africa",
  Georgia: "Asia",
  Germany: "Europe",
  Ghana: "Africa",
  Gibraltar: "Europe",
  Greece: "Europe",
  Greenland: "Americas",
  Grenada: "Americas",
  Guadeloupe: "Americas",
  Guam: "Oceania",
  Guatemala: "Americas",
  Guernsey: "Europe",
  Guinea: "Africa",
  "Guinea-Bissau": "Africa",
  Guyana: "Americas",
  Haiti: "Americas",
  "Heard Island and McDonald Islands": "Antarctic",
  Honduras: "Americas",
  "Hong Kong": "Asia",
  Hungary: "Europe",
  Iceland: "Europe",
  India: "Asia",
  Indonesia: "Asia",
  Iran: "Asia",
  Iraq: "Asia",
  Ireland: "Europe",
  "Isle of Man": "Europe",
  Israel: "Asia",
  Italy: "Europe",
  "Ivory Coast": "Africa",
  Jamaica: "Americas",
  Japan: "Asia",
  Jersey: "Europe",
  Jordan: "Asia",
  Kazakhstan: "Asia",
  Kenya: "Africa",
  Kiribati: "Oceania",
  Kosovo: "Europe",
  Kuwait: "Asia",
  Kyrgyzstan: "Asia",
  Laos: "Asia",
  Latvia: "Europe",
  Lebanon: "Asia",
  Lesotho: "Africa",
  Liberia: "Africa",
  Libya: "Africa",
  Liechtenstein: "Europe",
  Lithuania: "Europe",
  Luxembourg: "Europe",
  Macau: "Asia",
  Madagascar: "Africa",
  Malawi: "Africa",
  Malaysia: "Asia",
  Maldives: "Asia",
  Mali: "Africa",
  Malta: "Europe",
  "Marshall Islands": "Oceania",
  Martinique: "Americas",
  Mauritania: "Africa",
  Mauritius: "Africa",
  Mayotte: "Africa",
  Mexico: "Americas",
  Micronesia: "Oceania",
  Moldova: "Europe",
  Monaco: "Europe",
  Mongolia: "Asia",
  Montenegro: "Europe",
  Montserrat: "Americas",
  Morocco: "Africa",
  Mozambique: "Africa",
  Myanmar: "Asia",
  Namibia: "Africa",
  Nauru: "Oceania",
  Nepal: "Asia",
  Netherlands: "Europe",
  "New Caledonia": "Oceania",
  "New Zealand": "Oceania",
  Nicaragua: "Americas",
  Niger: "Africa",
  Nigeria: "Africa",
  Niue: "Oceania",
  "Norfolk Island": "Oceania",
  "North Korea": "Asia",
  "North Macedonia": "Europe",
  "Northern Mariana Islands": "Oceania",
  Norway: "Europe",
  Oman: "Asia",
  Pakistan: "Asia",
  Palau: "Oceania",
  Palestine: "Asia",
  Panama: "Americas",
  "Papua New Guinea": "Oceania",
  Paraguay: "Americas",
  Peru: "Americas",
  Philippines: "Asia",
  "Pitcairn Islands": "Oceania",
  Poland: "Europe",
  Portugal: "Europe",
  "Puerto Rico": "Americas",
  Qatar: "Asia",
  "Réunion": "Africa",
  Romania: "Europe",
  Russia: "Europe",
  Rwanda: "Africa",
  "Saint Barthélemy": "Americas",
  "Saint Helena, Ascension and Tristan da Cunha": "Africa",
  "Saint Kitts and Nevis": "Americas",
  "Saint Lucia": "Americas",
  "Saint Martin": "Americas",
  "Saint Pierre and Miquelon": "Americas",
  "Saint Vincent and the Grenadines": "Americas",
  Samoa: "Oceania",
  "San Marino": "Europe",
  "São Tomé and Príncipe": "Africa",
  "Saudi Arabia": "Asia",
  Senegal: "Africa",
  Serbia: "Europe",
  Seychelles: "Africa",
  "Sierra Leone": "Africa",
  Singapore: "Asia",
  "Sint Maarten": "Americas",
  Slovakia: "Europe",
  Slovenia: "Europe",
  "Solomon Islands": "Oceania",
  Somalia: "Africa",
  "South Africa": "Africa",
  "South Georgia": "Antarctic",
  "South Korea": "Asia",
  "South Sudan": "Africa",
  Spain: "Europe",
  "Sri Lanka": "Asia",
  Sudan: "Africa",
  Suriname: "Americas",
  "Svalbard and Jan Mayen": "Europe",
  Sweden: "Europe",
  Switzerland: "Europe",
  Syria: "Asia",
  Taiwan: "Asia",
  Tajikistan: "Asia",
  Tanzania: "Africa",
  Thailand: "Asia",
  "Timor-Leste": "Asia",
  Togo: "Africa",
  Tokelau: "Oceania",
  Tonga: "Oceania",
  "Trinidad and Tobago": "Americas",
  Tunisia: "Africa",
  "Türkiye": "Asia",
  Turkmenistan: "Asia",
  "Turks and Caicos Islands": "Americas",
  Tuvalu: "Oceania",
  Uganda: "Africa",
  Ukraine: "Europe",
  "United Arab Emirates": "Asia",
  "United Kingdom": "Europe",
  "United States": "Americas",
  "United States Minor Outlying Islands": "Americas",
  "United States Virgin Islands": "Americas",
  Uruguay: "Americas",
  Uzbekistan: "Asia",
  Vanuatu: "Oceania",
  "Vatican City": "Europe",
  Venezuela: "Americas",
  Vietnam: "Asia",
  "Wallis and Futuna": "Oceania",
  "Western Sahara": "Africa",
  Yemen: "Asia",
  Zambia: "Africa",
  Zimbabwe: "Africa",
  Turkey: "Asia", // alias for Türkiye
  "Czech Republic": "Europe", // alias for Czechia
  Swaziland: "Africa", // alias for Eswatini
  Burma: "Asia", // alias for Myanmar
  Macedonia: "Europe", // alias for North Macedonia
  "Democratic Republic of the Congo": "Africa", // alias for DR Congo
};

// Countries are free text (no picker — see AddressFields.jsx), so a typo
// or unusual spelling won't resolve to a continent. Returns null rather
// than guessing, same failure mode as the country filter itself: the
// partner just won't match a continent filter, but isn't hidden from
// "All Continents".
export function getContinent(countryName) {
  return COUNTRY_CONTINENTS[countryName] || null;
}
