-- Moves file storage from S3 (a URL/key pointing at an external object)
-- to storing the file bytes directly in Postgres. See the comment on the
-- Newsletter model in schema.prisma for why.
--
-- Existing Document/Newsletter/Photo rows only ever held a pointer to an
-- S3 object (fileKey/url) -- once this ships, the app no longer knows how
-- to reach S3 at all, so those pointers become permanently unusable
-- regardless of what happens here. Rather than add the new `bytes` column
-- as nullable (which would leave every pre-existing row broken forever,
-- with no way to tell "broken" apart from "legitimately empty"), this
-- clears those three tables outright and adds `bytes` as required. Safe
-- everywhere this has actually been deployed (production has no data yet;
-- demo's is synthetic and gets regenerated by the nightly reset job) --
-- see CHANGELOG.md for this release if a real deployment ever needs to
-- weigh this tradeoff differently.
DELETE FROM "Document";
DELETE FROM "Newsletter";
DELETE FROM "Photo";

-- AlterTable
ALTER TABLE "ChurchSettings" DROP COLUMN "logo",
ADD COLUMN     "logoBytes" BYTEA,
ADD COLUMN     "logoContentType" TEXT;

-- AlterTable
ALTER TABLE "Document" DROP COLUMN "fileKey",
ADD COLUMN     "bytes" BYTEA NOT NULL;

-- AlterTable
ALTER TABLE "Newsletter" DROP COLUMN "fileKey",
ADD COLUMN     "bytes" BYTEA NOT NULL;

-- AlterTable
ALTER TABLE "Photo" DROP COLUMN "url",
ADD COLUMN     "bytes" BYTEA NOT NULL;
